app/views/quiz.py
# flake8: noqa E712
from flask import (
    Blueprint,
    render_template,
    request,
    flash,
    redirect,
    url_for,
)
from flask_login import login_required, current_user
import sqlalchemy as sa
from app.controllers import create_pagination

from app.common import models as m
from app import forms as f
from app.logger import log
from app.database import db
from app.controllers import ActionLogs


bp = Blueprint("quiz", __name__, url_prefix="/quiz")


@bp.route("/", methods=["GET"])
@login_required
def get_all():
    q = request.args.get("q", type=str, default=None)
    query = (
        m.Question.select()
        .where(m.Question.is_deleted == False)
        .order_by(m.Question.id)
    )
    count_query = (
        sa.select(sa.func.count())
        .where(m.Question.is_deleted == False)
        .select_from(m.Question)
    )
    form = f.NewQuestionForm()
    if q:
        query = (
            m.Question.select()
            .where(
                sa.and_(m.Question.text.ilike(f"%{q}%"), m.Question.is_deleted == False)
            )
            .order_by(m.Question.id)
        )
        count_query = (
            sa.select(sa.func.count())
            .where(
                sa.and_(m.Question.text.ilike(f"%{q}%"), m.Question.is_deleted == False)
            )
            .select_from(m.Question)
        )
    total = db.session.scalar(count_query)
    pagination = create_pagination(total=db.session.scalar(count_query))

    return render_template(
        "quiz/quizes.html",
        questions=db.session.execute(
            query.offset((pagination.page - 1) * pagination.per_page).limit(
                pagination.per_page
            )
        ).scalars(),
        page=pagination,
        total=total,
        search_query=q,
        form=form,
    )


@bp.route("/get/<int:id>", methods=["GET"])
@login_required
def get(id: int):
    question: m.Question = db.session.scalar(
        m.Question.select().where(m.Question.id == id)
    )
    if not question:
        log(log.INFO, "There is no question with id: [%s]", id)
        flash("There is no such question", "danger")
        return "no question", 404

    return question.s_dict()


@bp.route("/save", methods=["POST"])
@login_required
def save():
    form = f.EditQuestionForm()
    if form.validate_on_submit():
        query = m.Question.select().where(m.Question.id == int(form.id.data))
        question: m.Question | None = db.session.scalar(query)
        if not question:
            log(log.ERROR, "Not found question by id : [%s]", form.id.data)
            flash("Cannot save question data", "danger")
            return redirect(url_for("quiz.get_all"))
        question.text = form.text.data
        question.correct_answer_mark = form.correct_answer_mark.data
        question.save()
        ActionLogs.create_question_log(m.ActionsType.EDIT, question.id)
        for i in range(1, 5):
            query = m.VariantAnswer.select().where(
                m.VariantAnswer.question_id == question.id,
                m.VariantAnswer.answer_mark == i,
            )
            variant: m.VariantAnswer | None = db.session.scalar(query)
            if not variant:
                log(log.ERROR, "Not found variant by id : [%s]", question.id)
                flash("Cannot save user data", "danger")
            else:
                variant.text = form[f"variant_{i}"].data
                db.session.add(variant)
                db.session.commit()
        log(log.ERROR, "Question saved!")
        flash("Question saved!", "success")
        return redirect(url_for("quiz.get_all"))
    else:
        log(log.ERROR, "Question save errors: [%s]", form.errors)
        flash(f"{form.errors}", "danger")
        return redirect(url_for("quiz.get_all"))


@bp.route("/create", methods=["POST"])
@login_required
def create():
    form = f.NewQuestionForm()
    if form.validate_on_submit():
        question = m.Question(
            text=form.text.data,
            correct_answer_mark=form.correct_answer_mark.data,
        )
        question.save()
        for i in range(1, 5):
            variant = m.VariantAnswer(
                question_id=question.id,
                text=form[f"variant_{i}"].data,
                answer_mark=i,
            )
            db.session.add(variant)
        db.session.commit()
        ActionLogs.create_question_log(m.ActionsType.CREATE, question.id)
        log(log.INFO, "Form submitted. Question: [%s]", question)
        flash("Question added!", "success")
        question.save()
        return redirect(url_for("quiz.get_all"))
    else:
        log(log.ERROR, "Question save errors: [%s]", form.errors)
        flash(f"{form.errors}", "danger")
        return redirect(url_for("quiz.get_all"))


@bp.route("/delete/<int:id>", methods=["DELETE"])
@login_required
def delete(id: int):
    question = db.session.scalar(m.Question.select().where(m.Question.id == id))
    if not question:
        log(log.INFO, "There is no question with id: [%s]", id)
        flash("There is no such question", "danger")
        return "no question", 404
    question.is_deleted = True
    db.session.commit()
    ActionLogs.create_question_log(m.ActionsType.DELETE, question.id)
    log(log.INFO, "question deleted. question: [%s]", question)
    flash("question deleted!", "success")
    return "ok", 200

app/templates/quiz/add.html
<!-- Adding user modal -->
<!-- prettier-ignore-->
<div id="addQuestionModal" tabindex="-1" aria-hidden="true" class="fixed top-0 left-0 right-0 z-50 items-center justify-center hidden w-full p-4 overflow-x-hidden overflow-y-auto md:inset-0 h-[calc(100%-1rem)] max-h-full">
  <div class="relative w-full max-w-2xl max-h-full">
    <!-- Modal content -->
    <form action="{{url_for('quiz.create')}}" method="post" class="relative bg-white rounded-lg shadow dark:bg-gray-700">
         {{ form.hidden_tag() }}
      <!-- Modal header -->
      <div class="flex items-start justify-between p-4 border-b rounded-t dark:border-gray-600">
        <h3 class="text-xl font-semibold text-gray-900 dark:text-white">Question {{total+1}}</h3>
      </div>
      <!-- Modal body -->
      <div class="p-6 space-y-6">
        <div class="grid grid-cols-1 gap-6">
          <div class="col-span-6 sm:col-span-3 flex flex-row items-center">
            <p class="mb-2 text-base font-medium text-gray-900 dark:text-white" >Text: </p >
            <textarea type="text" rows="2" name="text"  class="w-11/12 ml-auto shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-600 focus:border-blue-600 p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Text" required ></textarea>
          </div>
          <div class="col-span-6 sm:col-span-3 flex flex-row items-end">
            <label for="variant_1" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white" >1: </label >
            <input type="text" name="variant_1"  class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-600 focus:border-blue-600 block w-11/12 ml-auto p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" required />
          </div>
          <div class="col-span-6 sm:col-span-3 flex flex-row items-end">
            <label for="variant_2" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white" >2: </label >
            <input type="text" name="variant_2"  class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-600 focus:border-blue-600 block w-11/12 ml-auto p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" required />
          </div>
          <div class="col-span-6 sm:col-span-3 flex flex-row items-end">
            <label for="variant_3" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white" >3: </label >
            <input type="text" name="variant_3"  class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-600 focus:border-blue-600 block w-11/12 ml-auto p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" required />
          </div>
          <div class="col-span-6 sm:col-span-3 flex flex-row items-end">
            <label for="variant_4" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white" >4: </label >
            <input type="text" name="variant_4"  class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-600 focus:border-blue-600 block w-11/12 ml-auto p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" required />
          </div>
          <div class="col-span-6 sm:col-span-3">
            <select id="correct_answer_mark" name="correct_answer_mark" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" required>
              <option value=1>1</option>
              <option value=2>2</option>
              <option value=3>3</option>
              <option value=4>4</option>
            </select>
          </div>
        </div>
      </div>
      <!-- Modal footer -->
      <div class="flex items-center p-6 space-x-2 border-t border-gray-200 rounded-b dark:border-gray-600">
        <button name="submit" type="submit" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"> Save new question </button>
      </div>
    </form>
  </div>
</div>

app/templates/quiz/edit.html
<!-- Adding user modal -->
<!-- prettier-ignore-->
<div id="editQuestionModal" tabindex="-1" aria-hidden="true" class="fixed top-0 left-0 right-0 z-50 items-center justify-center hidden w-full p-4 overflow-x-hidden overflow-y-auto md:inset-0 h-[calc(100%-1rem)] max-h-full">
  <div class="relative w-full max-w-2xl max-h-full">
    <!-- Modal content -->
    <form action="{{url_for('quiz.save')}}" method="post" class="relative bg-white rounded-lg shadow dark:bg-gray-700">
         {{ form.hidden_tag() }}
         <input id="id" type="hidden" name="id" value="" />
         <input id="uuid" type="hidden" name="uuid" value="" />
      <!-- Modal header -->
      <div class="flex items-start justify-between p-4 border-b rounded-t dark:border-gray-600">
        <h3 class="text-xl font-semibold text-gray-900 dark:text-white" id="question-title"></h3>
      </div>
      <!-- Modal body -->
      <div class="p-6 space-y-6">
        <div class="grid grid-cols-1 gap-6">
          <div class="col-span-6 sm:col-span-3 flex flex-row items-center">
            <p class="mb-2 text-base font-medium text-gray-900 dark:text-white" >Text: </p >
            <textarea type="text" id="question-text" rows="2" name="text"  class="w-11/12 ml-auto shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-600 focus:border-blue-600 p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Text" required ></textarea>
          </div>
          <div class="col-span-6 sm:col-span-3 flex flex-row items-end">
            <label for="variant_1" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white" >1: </label >
            <input type="text" name="variant_1" id="question-variant-one" value=""  class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-600 focus:border-blue-600 block w-11/12 ml-auto p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" required />
          </div>
          <div class="col-span-6 sm:col-span-3 flex flex-row items-end">
            <label for="variant_2" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white" >2: </label >
            <input type="text" name="variant_2" id="question-variant-two" value=""  class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-600 focus:border-blue-600 block w-11/12 ml-auto p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" required />
          </div>
          <div class="col-span-6 sm:col-span-3 flex flex-row items-end">
            <label for="variant_3" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white" >3: </label >
            <input type="text" name="variant_3" id="question-variant-three" value=""  class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-600 focus:border-blue-600 block w-11/12 ml-auto p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" required />
          </div>
          <div class="col-span-6 sm:col-span-3 flex flex-row items-end">
            <label for="variant_4" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white" >4: </label >
            <input type="text" name="variant_4" id="question-variant-four" value=""  class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-600 focus:border-blue-600 block w-11/12 ml-auto p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" required />
          </div>
          <div class="col-span-6 sm:col-span-3">
            <select id="correct_answer_mark" name="correct_answer_mark" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" required>
              <option id="select_option_1">1</option>
              <option id="select_option_2">2</option>
              <option id="select_option_3">3</option>
              <option id="select_option_4">4</option>
            </select>
          </div>
        </div>
      </div>
      <!-- Modal footer -->
      <div class="flex items-center p-6 space-x-2 border-t border-gray-200 rounded-b dark:border-gray-600">
        <button name="submit" type="submit" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"> Save changes to question </button>
      </div>
    </form>
  </div>
</div>

app/templates/quiz/quizes.html
<!-- prettier-ignore -->
{% extends 'base.html' %}
{% block content %}
<div class="relative overflow-x-auto shadow-md sm:rounded-lg p-3">
  <div class="flex items-center justify-center py-4 bg-white dark:bg-gray-800">
    <label for="table-search" class="sr-only">Search</label>
    <div class="relative">
      <div
        class="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none"
      >

      <!-- prettier-ignore -->
        <svg class="w-5 h-5 text-gray-500 dark:text-gray-400" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z" clip-rule="evenodd"></path></svg>
      </div>
      <!-- prettier-ignore -->
      <input {% if search_query %}value={{ search_query }}{% endif %} type="text" id="table-search-question" class="block p-2 pl-10 text-sm text-gray-900 border border-gray-300 rounded-lg w-80 bg-gray-50 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Search for question"/>
    </div>
    <!-- prettier-ignore -->
    <button type="button"id="table-search-question-button" class="px-3 py-2 text-xs text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 ml-2 font-medium rounded-lg text-center inline-flex items-center mr-2 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"><svg class="w-5 h-5 text-white-500" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 ml-0 mr-1"><path stroke-linecap="round" stroke-linejoin="round" d="M15.75 15.75l-2.489-2.489m0 0a3.375 3.375 0 10-4.773-4.773 3.375 3.375 0 004.774 4.774zM21 12a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>Search</button>
    <div class="flex items-center ml-auto space-x-2 sm:space-x-3">
      <div class="text-xl text-gray-900 dark:text-white">
        Total: {{ total }}
      </div>
      <button type="button" id="add-question-btn" class="inline-flex items-center justify-center w-1/2 px-3 py-2 text-sm font-medium text-center text-white rounded-lg bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 sm:w-auto dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
        <svg class="w-5 h-5 mr-2 -ml-1" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M10 5a1 1 0 011 1v3h3a1 1 0 110 2h-3v3a1 1 0 11-2 0v-3H6a1 1 0 110-2h3V6a1 1 0 011-1z" clip-rule="evenodd"></path></svg>
        Add question
      </button>
    </div>
  </div>
  <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
    <thead
      class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400"
    >
      <tr>
        <th scope="col" class="px-6 py-3">#</th> <th scope="col" class="px-6 py-3">Name</th> <th scope="col" class="px-6 py-3">Actions</th>
      </tr>
    </thead>
    <tbody>
      {% for question in questions %}
      <tr
        class="bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600"
      >
      <td class="w-4 p-4">
        <div class="flex items-center">
              {{ question.id }}
            </div>
        </td>
        <td
          scope="row"
          class="flex items-center px-6 py-4 text-gray-900 whitespace-nowrap dark:text-white"
        >
          <div class="pl-3">
            <div class="text-base font-semibold">{{ question.text }}</div>
          </div>
        </td>
        <td class="p-4 space-x-2 whitespace-nowrap">
          <button type="button" id="edit-question-btn" data-question-id={{question.id}}  class="user-edit-button inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white rounded-lg bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
           <svg class="w-4 h-4 mr-2 " fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M17.414 2.586a2 2 0 00-2.828 0L7 10.172V13h2.828l7.586-7.586a2 2 0 000-2.828z"></path><path fill-rule="evenodd" d="M2 6a2 2 0 012-2h4a1 1 0 010 2H4v10h10v-4a1 1 0 112 0v4a2 2 0 01-2 2H4a2 2 0 01-2-2V6z" clip-rule="evenodd"></path></svg>
            Edit question
          </button>
          <button data-question-id={{ question.id }} type="button" class="inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white bg-red-600 rounded-lg hover:bg-red-800 focus:ring-4 focus:ring-red-300 dark:focus:ring-red-900 delete-question-btn">
          <svg class="w-4 h-4 mr-2" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z" clip-rule="evenodd"></path></svg>
             Delete question
          </button>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

{% if page.pages > 1 %}
<div class="container content-center mt-3 flex bg-white dark:bg-gray-800">
  <nav aria-label="Page navigation example" class="mx-auto">
    <ul class="inline-flex items-center -space-x-px">
      <li>
        <!-- prettier-ignore -->
        <a href="{{ url_for('quiz.get_all') }}?page=1&q={{page.query}}" class="block px-3 py-2 ml-0 leading-tight text-gray-500 bg-white border border-gray-300 rounded-l-lg hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white">
          <span class="sr-only">First</span>
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="w-5 h-5">
            <path fill-rule="evenodd" d="M15.79 14.77a.75.75 0 01-1.06.02l-4.5-4.25a.75.75 0 010-1.08l4.5-4.25a.75.75 0 111.04 1.08L11.832 10l3.938 3.71a.75.75 0 01.02 1.06zm-6 0a.75.75 0 01-1.06.02l-4.5-4.25a.75.75 0 010-1.08l4.5-4.25a.75.75 0 111.04 1.08L5.832 10l3.938 3.71a.75.75 0 01.02 1.06z" clip-rule="evenodd" />
          </svg>
        </a>
      </li>
      <li>
        <!-- prettier-ignore -->
        <a href="{{ url_for('quiz.get_all') }}?page={{page.page-1 if page.page > 1 else 1}}&q={{page.query}}" class="block px-3 py-2 ml-0 leading-tight text-gray-500 bg-white border border-gray-300 rounded-l-lg hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white">
          <span class="sr-only">Previous</span>
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="w-5 h-5">
            <path fill-rule="evenodd" d="M12.79 5.23a.75.75 0 01-.02 1.06L8.832 10l3.938 3.71a.75.75 0 11-1.04 1.08l-4.5-4.25a.75.75 0 010-1.08l4.5-4.25a.75.75 0 011.06.02z" clip-rule="evenodd" />
          </svg>
        </a>
      </li>

      <!-- prettier-ignore -->
      {% for p in page.pages_for_links %}
      <li>
        <!-- prettier-ignore -->
        {% if p == page.page %}
        <!-- prettier-ignore -->
        <a href="{{ url_for('quiz.get_all') }}?page={{p}}&q={{page.query}}" aria-current="page" class="z-10 px-3 py-2 leading-tight text-blue-600 border border-blue-300 bg-blue-50 hover:bg-blue-100 hover:text-blue-700 dark:border-gray-700 dark:bg-gray-700 dark:text-white">{{p}}</a>
        {% else %}
        <!-- prettier-ignore -->
        <a href="{{ url_for('quiz.get_all') }}?page={{p}}&q={{page.query}}" class="px-3 py-2 leading-tight text-gray-500 bg-white border border-gray-300 hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white">{{p}}</a>
        {% endif %}
      </li>
      {% endfor %}

      <li>
        <!-- prettier-ignore -->
        <a href="{{ url_for('quiz.get_all') }}?page={{page.page+1 if page.page < page.pages else page.pages}}&q={{page.query}}" class="block px-3 py-2 leading-tight text-gray-500 bg-white border border-gray-300 rounded-r-lg hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white">
          <!-- prettier-ignore -->
          <span class="sr-only">Next</span>
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="w-5 h-5">
            <path fill-rule="evenodd" d="M7.21 14.77a.75.75 0 01.02-1.06L11.168 10 7.23 6.29a.75.75 0 111.04-1.08l4.5 4.25a.75.75 0 010 1.08l-4.5 4.25a.75.75 0 01-1.06-.02z" clip-rule="evenodd" />
          </svg>
        </a>
      </li>
      <li>
        <!-- prettier-ignore -->
        <a href="{{ url_for('quiz.get_all') }}?page={{page.pages}}&q={{page.query}}" class="block px-3 py-2 leading-tight text-gray-500 bg-white border border-gray-300 rounded-r-lg hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white">
          <!-- prettier-ignore -->
          <span class="sr-only">Last</span>
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="w-5 h-5">
            <path fill-rule="evenodd" d="M10.21 14.77a.75.75 0 01.02-1.06L14.168 10 10.23 6.29a.75.75 0 111.04-1.08l4.5 4.25a.75.75 0 010 1.08l-4.5 4.25a.75.75 0 01-1.06-.02z" clip-rule="evenodd" />
            <path fill-rule="evenodd" d="M4.21 14.77a.75.75 0 01.02-1.06L8.168 10 4.23 6.29a.75.75 0 111.04-1.08l4.5 4.25a.75.75 0 010 1.08l-4.5 4.25a.75.75 0 01-1.06-.02z" clip-rule="evenodd" />
          </svg>
        </a>
      </li>
    </ul>
  </nav>
</div>
</div>
{% endif %}
</div>
{% include 'quiz/add.html' %}
{% include 'quiz/edit.html' %}
<!-- prettier-ignore -->
{% endblock %}