app/forms/case.py
import filetype

from flask_wtf import FlaskForm
from wtforms import (
    IntegerField,
    StringField,
    SubmitField,
    BooleanField,
    SelectMultipleField,
    widgets,
    FileField,
    MultipleFileField,
    ValidationError,
    SelectField,
)
from wtforms.validators import DataRequired, Length, URL, Optional
from app.common.models import Languages


class MultiCheckboxField(SelectMultipleField):
    widget = widgets.ListWidget(prefix_label=False)
    option_widget = widgets.CheckboxInput()


class CaseForm(FlaskForm):
    title = StringField("title", [DataRequired(), Length(2, 32)])
    sub_title = StringField("sub_title", [DataRequired(), Length(2, 64)])
    description = StringField("description", [DataRequired(), Length(1, 512)])
    is_active = BooleanField("is_active")
    is_main = BooleanField("is_main")
    project_link = StringField("project_link", validators=[Optional(), URL()])
    role = StringField("role", [DataRequired(), Length(2, 32)])
    stacks = MultiCheckboxField("stacks")

    submit = SubmitField("Save")

    def validate_stacks(form, field):
        if not field.data:
            raise ValidationError("Select at least one stack.")


class NewCaseForm(CaseForm):
    title_image = FileField("title_image", [DataRequired()])
    sub_title_image = FileField("sub_title_image", [DataRequired()])
    sub_images = MultipleFileField("sub_images", [DataRequired()])
    language = SelectField(
        "language",
        choices=[(lan.value, lan.name) for lan in Languages],
        validators=[DataRequired()],
    )


class UpdateCaseState(FlaskForm):
    field = StringField("filed")


class UpdateCase(CaseForm):
    case_id = IntegerField("case_id", [DataRequired()])
    stacks = MultiCheckboxField("stacks")
    title_image = FileField("title_image")
    sub_title_image = FileField("sub_title_image")
    sub_images = MultipleFileField("sub_images")

    def validate_title_image(self, field):
        if field.data:
            is_file = filetype.guess(field.data)
            if not is_file or not filetype.is_image(field.data):
                raise ValidationError("File must be an image")

    def validate_sub_title_image(self, field):
        if field.data:
            is_file = filetype.guess(field.data)
            if not is_file or not filetype.is_image(field.data):
                raise ValidationError("File must be an image")

    def validate_sub_images(self, field):
        for file in field.data:
            # when we not send any file it will come application/octet-stream
            if file.content_type == "application/octet-stream":
                continue
            is_file = filetype.guess(file)
            if not is_file or not filetype.is_image(file):
                raise ValidationError("File must be an image")


class CreateCaseCopy(FlaskForm):
    case_id = IntegerField("case_id", [DataRequired()])
    language = SelectField(
        "language",
        choices=[(lan.value, lan.name) for lan in Languages],
        validators=[DataRequired()],
    )

app/forms/stack.py
from flask_wtf import FlaskForm
from wtforms import (
    StringField,
)
from wtforms.validators import DataRequired, Length


class NewStackForm(FlaskForm):
    stacks = StringField("stacks", [DataRequired(), Length(2, 32)])

app/views/case.py
# flake8: noqa E712
from datetime import datetime

from flask import (
    Blueprint,
    render_template,
    request,
    flash,
    redirect,
    url_for,
    Response,
)
from flask_login import login_required
import sqlalchemy as sa
from werkzeug.datastructures import FileStorage
import botocore

from app.common.models.case_image import EnumCaseImageType
from app.controllers import create_pagination

from app.common import models as m
from app.common.models import Languages
from app import schema as s
from app import forms as f
from app.logger import log
from app.database import db
from app import s3bucket
from app.controllers import ActionLogs


bp = Blueprint("case", __name__, url_prefix="/case")


@bp.route("/", methods=["GET"])
@login_required
def get_all():

    form = f.NewCaseForm()
    copy_case_form = f.CreateCaseCopy()
    form.stacks.choices = [(str(s.id), s.name) for s in db.session.query(m.Stack).all()]
    q = request.args.get("q", type=str, default=None)
    lang_str = request.args.get("lang", type=str, default="")

    try:
        lang = Languages(lang_str)
    except ValueError:
        lang = None

    query = (
        m.Case.select()
        .where(
            m.Case.is_deleted == sa.false(),
        )
        .order_by(m.Case.id)
    )
    if lang:
        query = query.where(m.Case.language == lang)
    if q:
        query = query.where(m.Case.title.ilike(f"%{q}%"))

    pagination = create_pagination(
        total=db.session.scalar(
            sa.select(sa.func.count()).select_from(query.subquery())
        )
    )

    return render_template(
        "case/cases.html",
        cases=db.session.execute(
            query.offset((pagination.page - 1) * pagination.per_page).limit(
                pagination.per_page
            )
        ).scalars(),
        page=pagination,
        search_query=q,
        form=form,
        copy_case_form=copy_case_form,
        options=[(lan.name, lan.value) for lan in m.Languages],
    )


@bp.route("/<int:id>", methods=["GET"])
@login_required
def get_case(id: int):
    case: m.Case = db.session.scalar(m.Case.select().where(m.Case.id == id))
    if not case:
        log(log.INFO, "There is no case with id: [%s]", id)
        flash("There is no such case", "danger")
        return "no case", 404

    return s.CaseOut.from_orm(case).json(by_alias=True)


@bp.route("/copy", methods=["POST"])
@login_required
def create_copy_case():
    form = f.CreateCaseCopy()
    if not form.validate_on_submit():
        log(log.ERROR, "Case errors: [%s]", form.errors)
        flash(f"{form.errors}", "danger")
        return redirect(url_for("case.get_all"))

    case = db.session.get(m.Case, form.case_id.data)
    lang = Languages(form.language.data)
    if not case or case.language == lang:
        log(
            log.ERROR,
            "Case not found or case with language: [%s] already exist",
            form.language.data,
        )
        flash(
            f"Case not found or case with language: {form.case_id.data} already exist",
            "danger",
        )
        return redirect(url_for("case.get_all"))

    copy_case = m.Case(
        title=case.title,
        sub_title=case.sub_title,
        description=case.description,
        language=lang,
        role=case.role,
        project_link=case.project_link,
    )
    db.session.add(copy_case)
    db.session.commit()
    for case_stack in case._stacks:
        copy_case._stacks.append(case_stack)
    for case_screenshot in case._screenshots:
        copy_case_screenshot = m.CaseScreenshot(
            case_id=copy_case.id,
            url=case_screenshot.url,
            origin_file_name=case_screenshot.origin_file_name,
        )
        db.session.add(copy_case_screenshot)

    for case_image in db.session.scalars(
        case.case_images.select().where(m.CaseImage.is_deleted.is_(False))
    ):
        copy_case_images = m.CaseImage(
            case_id=copy_case.id,
            url=case_image.url,
            type_of_image=case_image.type_of_image,
            origin_file_name=case_image.origin_file_name,
        )
        db.session.add(copy_case_images)
    db.session.commit()
    log(log.INFO, "Case copy created")
    ActionLogs.create_case_log(m.ActionsType.EDIT, copy_case.id)
    flash(f"Case copy created", "success")
    return redirect(url_for("case.get_all"))


@bp.route("/create", methods=["POST"])
@login_required
def create():
    form = f.NewCaseForm()
    form.stacks.choices = [(str(s.id), s.name) for s in db.session.query(m.Stack).all()]
    if not form.validate_on_submit():
        log(log.ERROR, "Case errors: [%s]", form.errors)
        flash(f"{form.errors}", "danger")
        return redirect(url_for("case.get_all"))
    log(log.INFO, "Form submitted. Case: [%s]", form)
    session = db.session

    title: str = form.title.data
    main_image_obj: FileStorage = form.title_image.data
    preview_image_obj: FileStorage = form.sub_title_image.data
    case_screenshots: list[FileStorage] = form.sub_images.data

    try:
        main_image_url = s3bucket.upload_cases_imgs(
            file=main_image_obj,
            file_name=main_image_obj.filename or "unknown.jpg",
            case_name=title,
            img_type=EnumCaseImageType.case_main_image.value,
        )
        preview_image_url = s3bucket.upload_cases_imgs(
            file=preview_image_obj,
            file_name=preview_image_obj.filename or "unknown.jpg",
            case_name=title,
            img_type=EnumCaseImageType.case_preview_image.value,
        )

        if not main_image_url or not preview_image_url:
            flash("No uploaded image", "danger")
            return redirect(url_for("case.get_all"))
        screenshots_urls: list[str] = []

        for screenshot in case_screenshots:
            file_image = s3bucket.upload_cases_imgs(
                file=screenshot,
                file_name=screenshot.filename or "unknown.jpg",
                case_name=title,
                img_type="screenshots",
            )
            screenshots_urls.append(file_image)
    except TypeError as error:
        flash(error.args[0], "danger")
        return redirect(url_for("case.get_all"))
    try:
        lang = Languages(form.language.data)
    except ValueError:
        lang = Languages.ENGLISH

    new_case = m.Case(
        title=form.title.data,
        sub_title=form.sub_title.data,
        description=form.description.data,
        is_active=form.is_active.data,
        is_main=form.is_main.data,
        project_link=form.project_link.data,
        role=form.role.data,
        language=lang,
    )
    session.add(new_case)
    session.commit()
    session.refresh(new_case)
    ActionLogs.create_case_log(m.ActionsType.CREATE, new_case.id)

    for index, img in enumerate(screenshots_urls):
        new_screenshot = m.CaseScreenshot(
            url=img,
            case_id=new_case.id,
            origin_file_name=f"screenshot_{index}",
        )

        session.add(new_screenshot)

    new_main_image = m.CaseImage(
        url=main_image_url,
        origin_file_name=main_image_obj.filename,
        case_id=new_case.id,
        type_of_image=EnumCaseImageType.case_main_image,
    )
    new_preview_image = m.CaseImage(
        url=preview_image_url,
        origin_file_name=preview_image_obj.filename,
        case_id=new_case.id,
        type_of_image=EnumCaseImageType.case_preview_image,
    )

    session.add(new_main_image)
    session.add(new_preview_image)

    for id in form.stacks.data:
        new_stack = m.CaseStack(case_id=new_case.id, stack_id=int(id))
        session.add(new_stack)
    session.commit()

    # notify_case_created(new_case) this will be provided in new version
    log(log.INFO, "Case created. Case: [%s]", new_case)
    flash("Case added!", "success")
    return redirect(url_for("case.get_all"))


@bp.route("/update-status/<int:id>", methods=["PATCH"])
@login_required
def update_case_status(id: int):
    form = f.UpdateCaseState()
    case = db.session.get(m.Case, id)

    if not case:
        log(log.INFO, "There is no case with id: [%s]", id)
        flash("There is no such case", "danger")
        return "no case", 404

    if not form.validate_on_submit():
        log(log.ERROR, "Case errors: [%s]", form.errors)
        flash(f"{form.errors}", "danger")
        return "error", 422

    field = form.field.data
    if field == "is_active":
        case.is_active = not case.is_active
    if field == "is_main":
        case.is_main = not case.is_main
    db.session.commit()
    log(log.INFO, "Case updated. Case: [%s]", case)
    ActionLogs.create_case_log(m.ActionsType.EDIT, case.id)
    flash("Case updated!", "success")
    return "ok", 200


@bp.route("/update", methods=["POST"])
@login_required
def update_case():
    form = f.UpdateCase()
    form.stacks.choices = [(str(s.id), s.name) for s in db.session.query(m.Stack).all()]
    if not form.validate_on_submit():
        log(log.ERROR, "Case errors: [%s]", form.errors)
        flash(f"{form.errors}", "danger")
        return redirect(url_for("case.get_all"))
    case = db.session.get(m.Case, form.case_id.data)
    if not case:
        log(log.INFO, "There is no case with id: [%s]", form.case_id.data)
        flash("There is no such case", "danger")
        return redirect(url_for("case.get_all"))

    main_image_obj: FileStorage = form.title_image.data
    if main_image_obj:
        try:
            s3bucket.delete_cases_imgs(case.main_image_url)
        except botocore.exceptions.ClientError as error:
            log(log.ERROR, "Can't delete main image in case: [%s]", case.id)
            flash(error.args[0], "danger")
            return redirect(url_for("case.get_all"))
        try:
            main_image_url = s3bucket.upload_cases_imgs(
                file=main_image_obj,
                file_name=main_image_obj.filename or "unknown.jpg",
                case_name=form.title.data,

app/views/stack.py
# flake8: noqa E712
from flask import Blueprint, request, flash
from flask_login import login_required


from app.common import models as m
from app import forms as f
from app.logger import log
from app.database import db


bp = Blueprint("stack", __name__, url_prefix="/stack")


@bp.route("/create", methods=["POST"])
@login_required
def create():
    form = f.NewStackForm(request.form)

    if form.validate_on_submit():
        stacks = form.stacks.data.split(",")
        for stack in stacks:
            new_stack = m.Stack(name=stack)
            db.session.add(new_stack)
            db.session.commit()
    else:
        flash("Invalid form data or stack exist", "danger")
        return "ok", 422

    log(log.INFO, "Stack created!. Stack: [%s]", new_stack.name)
    flash("Stack created!", "success")
    return "ok", 200


@bp.route("/delete/<int:stack_id>", methods=["DELETE"])
@login_required
def delete(stack_id):
    stack = db.session.get(m.Stack, stack_id)
    if not stack:
        log(log.INFO, "Deletion failed. Stack not found: [%d]", stack_id)
        flash("Deletion failed stack not found", "danger")
        return "ok", 404

    if stack._cases:
        log(log.INFO, "Deletion failed. Stack in use: [%d]", stack_id)
        flash(
            f"Deletion failed stack are using in Cases {' , '.join(map(str, stack._cases))}",
            "danger",
        )
        return "ok", 422

    db.session.delete(stack)
    db.session.commit()

    log(log.INFO, "Stack deleted!. Stack: [%s]", stack)
    flash("Successfully deleted!", "success")
    return "ok", 200

app/templates/case/edit.html
<!-- Edit user modal -->
<!-- prettier-ignore-->
<div id="caseEditModalElement" tabindex="-1" aria-hidden="true"
  class="fixed top-0 left-0 right-0 z-50 items-center justify-center hidden w-full p-4 overflow-x-hidden overflow-y-auto md:inset-0 h-[calc(100%-1rem)] max-h-full">
  <div class="relative w-full max-w-2xl max-h-full">
    <!-- Modal content -->
    <div class="flex items-start justify-between p-4 border-b rounded-t-lg dark:border-gray-600  bg-white shadow dark:bg-gray-700">
      <h3 class="text-xl font-semibold text-gray-900 dark:text-white"> Edit case </h3>
      <div class="flex gap-4 items-center justify-center">
        <form action="{{url_for('case.create_copy_case')}}" method="POST">
          <button type="submit" class="text-gray-900 bg-white border border-gray-300 focus:outline-none hover:bg-gray-100 focus:ring-4 focus:ring-gray-200 font-medium rounded-lg text-sm px-5 py-2.5 dark:bg-gray-800 dark:text-white dark:border-gray-600 dark:hover:bg-gray-700 dark:hover:border-gray-600 dark:focus:ring-gray-700">Create copy</button>
          {{ copy_case_form.hidden_tag() }}
          <input id="caseIdEditCopy" type="hidden" name="case_id" value="" />
          {{ copy_case_form.language }}
        </form>
      </div>
    </div>
    <form action="{{url_for('case.update_case')}}" method="POST" enctype="multipart/form-data"
      class="relative bg-white rounded-b-lg shadow dark:bg-gray-700">
      <!-- Modal header -->
      {{ form.hidden_tag() }}
      <!-- Modal body -->
      <div class="p-6 space-y-6">
        <div class="grid grid-cols-6 gap-6">
          <div  class="col-span-6 sm:col-span-3">
            <input id="caseIdEdit" type="hidden" name="case_id" value="" />
            <label for="title" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Title<span
                class="text-red-500">*</span></label>
            <input id="edit-case-title" type="text" name="title"
              class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-600 focus:border-blue-600 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
              placeholder="Title" required />
          </div>
          <div  class="col-span-6 sm:col-span-3">
            <label for="sub_title" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Sub title<span class="text-red-500">*</span></label>
            </label>
            <input id="edit-case-sub-title" type="text" name="sub_title"
              class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-600 focus:border-blue-600 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
              placeholder="Sub title" required />
          </div>

          <div class="col-span-6 sm:col-span-3 "><img id="edit-case-main-image" class="max-h-48" src="" alt=""></div>
          <div class="col-span-6 sm:col-span-3 "><img id="edit-case-preview-image" class="max-h-48" src="" alt=""></div>
          <div class="col-span-6 sm:col-span-3">
            <label class="block mb-2 text-sm font-medium text-gray-900 dark:text-white"
              title="This image will be displayed on the Case single page">Upload main
              image<span class="text-red-500">*</span></label>
            <input id="edit-case-main-image-input" type="file" name="title_image"  accept="image/*">
          </div>
          <div class="col-span-6 sm:col-span-3">
            <label class="block mb-2 text-sm font-medium text-gray-900 dark:text-white"
              title="This image will be displayed in the lists of Cases">Upload preview image<span
                class="text-red-500">*</span></label>
            <input id="edit-case-sub-main-image-input" type="file" name="sub_title_image"  accept="image/*">
          </div>

          <div class="col-span-6 sm:col-span-3">
            <label for="description"
              class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Description<span
                class="text-red-500">*</span></label>
            <input id="edit-case-description" type="text" name="description"
              class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-600 focus:border-blue-600 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
              placeholder="Description" required />
          </div>
          <div class="col-span-6 sm:col-span-3 flex justify-evenly">
            <label for="is_active" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white"
              title="Will Case be displayed on the site">Is
              active</label>
            <input id="edit-case-is-active" type="checkbox" name="is_active"
              class="shadow-sm bg-gray-50 border border-gray-300 text-green-500 text-sm rounded-lg focus:ring-green-500 focus:border-green-500 block p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white dark:focus:ring-green-500 dark:focus:border-green-500" />
            <label for="is_main" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white"
              title="Will the Item be displayed on the main page of the site (or only in Cases)">Is main</label>
            <input id="edit-case-is-main" type="checkbox" name="is_main"
              class="shadow-sm bg-gray-50 border border-gray-300 text-green-500 text-sm rounded-lg focus:ring-green-500 focus:border-green-500 block p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white dark:focus:ring-green-500 dark:focus:border-green-500" />
          </div>
          <div class="col-span-full">
            <label for="project_link" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Project
              link<span class="text-red-500">*</span></label>
            <input id="edit-case-project-link" type="url" pattern="https://.*" name="project_link"
              class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-600 focus:border-blue-600 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
              placeholder="https://some.com" />
          </div>
          <div class="col-span-full">
            <label for="role" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Our
              role<span class="text-red-500">*</span></label>
            <input id="edit-case-role" type="role" name="role"
              class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-600 focus:border-blue-600 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
              placeholder="Type here" required  />
          </div>
          <div class="col-span-full">
            <label for="role" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Stacks</label>
            <div id="edit-case-stacks"
              class="max-h-24 p-2.5 overflow-y-auto shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-600 focus:border-blue-600 block w-full dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
              {{ form.stacks }}
            </div>
          </div>

          <div class="col-span-6 sm:col-span-3">
            <label class="block mb-2 text-sm font-medium text-gray-900 dark:text-white"
              title="Screenshots of the current Case will be displayed on its page">Upload screenshots<span
                class="text-red-500">*</span></label>
            <input type="file" name="sub_images" multiple accept="image/*">
          </div>
          <div id="edit-case-screenshots" class="col-span-6 sm:col-span-3 overflow-x-scroll h-52 p-4"></div>
        </div>
      </div>
      <!-- Modal footer -->
      <div class="flex items-center p-6 space-x-2 border-t border-gray-200 rounded-b dark:border-gray-600">
        <button id="edit-case-submit-btn" name="submit" type="submit"
          class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
          Save </button>
      </div>
    </form>
  </div>
</div>

app/templates/case/stack.html
<!-- Adding user modal -->
<!-- prettier-ignore-->
<div id="stackModal" tabindex="-1" aria-hidden="true"
  class="fixed top-0 left-0 right-0 z-50 items-center justify-center hidden w-full p-4 overflow-x-hidden overflow-y-auto md:inset-0 h-[calc(100%-1rem)] max-h-full">
  <div class="relative w-full max-w-2xl max-h-full">
    <!-- Modal content -->
    <form id="add-stack-form" method="post" enctype="multipart/form-data"
      class="relative bg-white rounded-lg shadow dark:bg-gray-700">
      <!-- Modal header -->
      {{ form.hidden_tag() }}
      <div class="flex items-start justify-between p-4 border-b rounded-t dark:border-gray-600">
        <h3 class="text-xl font-semibold text-gray-900 dark:text-white"> Add new stack </h3>
      </div>
      <!-- Modal body -->
      <div class="p-6 space-y-6">
        <div class="grid grid-cols-6 gap-6">
          <div class="col-span-6 sm:col-span-3">
            <label for="name" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Name</label>
            <input type="text" id="add-stack-form-input" name="name"
              class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-600 focus:border-blue-600 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
              placeholder="Type name" />
          </div>
        </div>
      </div>
      <div class="w-full px-4 py-2 flex flex-wrap gap-1" id="add-stack-form-stacks">
        {% for id, name in form.stacks.choices %}
        <span id="{{name }}"
          class="flex gap-1 bg-indigo-200 text-indigo-800 text-lg font-medium mr-2 px-2.5 py-0.5 rounded dark:bg-gray-700 dark:text-indigo-400 border border-indigo-400">{{
          name }}
          <div id="delete-wrapper">
            <button id="button-{{id}}" type="button"
              class="text-red-600 bg-transparent hover:bg-red-400 hover:text-gray-900 rounded-lg text-sm p-1.5 ml-auto inline-flex items-center dark:hover:bg-gray-600 dark:hover:text-white">
              <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20"
                xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd"
                  d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z"
                  clip-rule="evenodd">
                </path>
              </svg>
            </button>
          </div>
        </span>


        {% endfor %}
      </div>
      <!-- Modal footer -->
      <div class="flex items-center p-6 space-x-2 border-t border-gray-200 rounded-b dark:border-gray-600">
        <button name="submit" type="submit"
          class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
          Add new stack(s)
        </button>
      </div>
    </form>
  </div>
</div>